# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memlake_client.v1 import memlake_pb2 as memlake_dot_v1_dot_memlake__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memlake/v1/memlake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemlakeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNamespace = channel.unary_unary(
                '/memlake.v1.Memlake/CreateNamespace',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceResponse.FromString,
                _registered_method=True)
        self.DeleteNamespace = channel.unary_unary(
                '/memlake.v1.Memlake/DeleteNamespace',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.DeleteNamespaceRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.DeleteNamespaceResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/memlake.v1.Memlake/Write',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.WriteRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/memlake.v1.Memlake/Query',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.QueryRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/memlake.v1.Memlake/ListNamespaces',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/memlake.v1.Memlake/Stats',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.StatsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/memlake.v1.Memlake/Get',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.GetRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.GetResponse.FromString,
                _registered_method=True)
        self.EntityStats = channel.unary_unary(
                '/memlake.v1.Memlake/EntityStats',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.EntityStatsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.EntityStatsResponse.FromString,
                _registered_method=True)
        self.MetadataStats = channel.unary_unary(
                '/memlake.v1.Memlake/MetadataStats',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.MetadataStatsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.MetadataStatsResponse.FromString,
                _registered_method=True)
        self.LinkStats = channel.unary_unary(
                '/memlake.v1.Memlake/LinkStats',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.LinkStatsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.LinkStatsResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/memlake.v1.Memlake/Scan',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.ScanRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.DeleteByPredicate = channel.unary_unary(
                '/memlake.v1.Memlake/DeleteByPredicate',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateResponse.FromString,
                _registered_method=True)
        self.ListWal = channel.unary_unary(
                '/memlake.v1.Memlake/ListWal',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.ListWalRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.ListWalResponse.FromString,
                _registered_method=True)
        self.IndexLayout = channel.unary_unary(
                '/memlake.v1.Memlake/IndexLayout',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.IndexLayoutRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.IndexLayoutResponse.FromString,
                _registered_method=True)
        self.CacheStats = channel.unary_unary(
                '/memlake.v1.Memlake/CacheStats',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.CacheStatsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.CacheStatsResponse.FromString,
                _registered_method=True)
        self.ListObjects = channel.unary_unary(
                '/memlake.v1.Memlake/ListObjects',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.ListObjectsResponse.FromString,
                _registered_method=True)
        self.DecodeObject = channel.unary_unary(
                '/memlake.v1.Memlake/DecodeObject',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.DecodeObjectRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.DecodeObjectResponse.FromString,
                _registered_method=True)


class MemlakeServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateNamespace(self, request, context):
        """Ensure a namespace (bank) exists. Idempotent: safe to call on every startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNamespace(self, request, context):
        """Drop a whole namespace: delete every object under its prefix (manifest, WAL, all
        generations). Irreversible. The manifest is deleted first, which fences a concurrent
        indexer — an in-flight fold loses its CAS publish and cannot leave a dangling manifest
        that points at swept files. The drop is still not transactional, though: a query racing
        the delete may fault on a since-deleted file, so dropping under active writes is
        discouraged. Returns the number of objects removed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write a batch of ops as one atomic WAL entry. Returns once the entry is durably
        persisted to object storage under a uniquely-claimed sequence number. The write is
        immediately visible to any Query without waiting for the indexer: a read always merges
        the un-indexed WAL tail over the indexed generation. Set `wait_for_index` to also fold
        the tail into the generation before returning (a heavier, synchronous call).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Answer a query across one or more memory_types in a single call. Reads reflect every
        acked write: the snapshot checks the WAL head and scans the un-indexed tail over the
        indexed generation. Always runs all three arms (dense vector + BM25 full-text + graph
        expansion) over one shared snapshot, so the storage reads coalesce into common roundtrip
        waves. Returns each candidate with its raw per-arm scores; the client fuses. memory_types
        are independent — hits are never fused across types.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """---- Admin / introspection ----

        These serve operators and the admin UI, not the hot path. They are answerable by any
        replica for the same reason every other RPC is: the answer lives in object storage.
        They are deliberately NOT part of the retrieval contract — a client doing recall
        should never need them.

        Every namespace in the bucket, by listing manifest objects. Cost is one LIST, so this
        is an operator call, not something to poll per request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """A namespace's index state: generation, WAL position, and per-memory_type doc and
        cluster counts. Reads the manifest and each type's metadata — it does NOT fetch
        cluster data, so its cost is independent of corpus size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Fetch memories by id, without a query. Resolves each id through the primary-key
        SSTable to its cluster, then range-reads only those clusters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EntityStats(self, request, context):
        """How many memories carry each entity. Reads the entity posting index — the same
        structure the graph arm expands through — so its cost scales with the number of
        entities, not the corpus. Counts reflect the indexed generation plus the un-indexed
        WAL tail, the same adjustment `Stats.doc_count` makes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MetadataStats(self, request, context):
        """Live item count per distinct value of one declared metadata key (see
        CreateNamespace.indexed_metadata_keys) — the primitive behind "count memories grouped by
        document_id / consolidated". Read from the per-segment tally, so it is a metadata read,
        not a corpus scan. Counts reflect the indexed generation plus the WAL tail, the same
        adjustment Stats.doc_count and EntityStats make. Empty for a key that was not declared.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkStats(self, request, context):
        """Live edge totals — derived semantic (kNN) links and intrinsic causal links — across a
        namespace. Read from the per-segment tally plus the WAL tail (the same adjustment
        Stats.doc_count and MetadataStats make), so it is a metadata read, not a corpus scan. The
        primitive behind the bank stats page's link count.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Page through a memory_type's stored memories in cluster order. This is a full scan by
        construction — the cost DOES grow with the corpus — so it exists for browsing and
        debugging, never for retrieval. Use `Query` to find things.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByPredicate(self, request, context):
        """Tombstone every memory matching a predicate. The predicate is metadata AND tags (all
        must hold), e.g. `{document_id, chunk_id}` to replace a document's facts on re-ingest.
        A full scan by construction (metadata is not indexed) — a maintenance op, not a query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWal(self, request, context):
        """The write-ahead log as an operator view: which sequences are committed, and which the
        indexer has not folded yet. Entries at or below the manifest's `wal_index_cursor` are
        folded and may already have been reclaimed by GC, so this is a window on the live log,
        not a history of every write ever made.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexLayout(self, request, context):
        """How k-means partitioned one memory_type: its trained centroids, per-cluster sizes and
        tag summaries, and optionally a sample of member memories. Centroids are already
        resident on every query node, so returning them alone costs no object-storage read;
        sampling members does read cluster files, and is bounded by `member_sample`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CacheStats(self, request, context):
        """What this replica is holding in its two-tier read cache, and how well it is working.

        UNLIKE EVERY OTHER RPC HERE, this one is NOT answerable by any replica: the cache is
        process-local, so the answer describes whichever pod the call happened to land on and
        two calls behind a load balancer will disagree. It is a node inspection tool, not a
        cluster-wide view. Nothing it reports affects correctness — a cold cache changes
        latency only (INV-4).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """Every object a namespace owns in object storage, classified by kind, with whether the
        current manifest still references it. This is the physical view — what is actually on
        S3 — as opposed to `Stats`, which is the logical one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecodeObject(self, request, context):
        """Decode one stored object into readable JSON. A debugging and teaching tool: it exists
        so an operator can see what is really inside a cluster file or a WAL entry, not as a
        data access path — reading memories is `Get`/`Scan`/`Query`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemlakeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespace,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceResponse.SerializeToString,
            ),
            'DeleteNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNamespace,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.DeleteNamespaceRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.DeleteNamespaceResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.WriteRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.WriteResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.QueryRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.QueryResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.StatsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.StatsResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.GetRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.GetResponse.SerializeToString,
            ),
            'EntityStats': grpc.unary_unary_rpc_method_handler(
                    servicer.EntityStats,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.EntityStatsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.EntityStatsResponse.SerializeToString,
            ),
            'MetadataStats': grpc.unary_unary_rpc_method_handler(
                    servicer.MetadataStats,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.MetadataStatsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.MetadataStatsResponse.SerializeToString,
            ),
            'LinkStats': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkStats,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.LinkStatsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.LinkStatsResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.ScanRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.ScanResponse.SerializeToString,
            ),
            'DeleteByPredicate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByPredicate,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateResponse.SerializeToString,
            ),
            'ListWal': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWal,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.ListWalRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.ListWalResponse.SerializeToString,
            ),
            'IndexLayout': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexLayout,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.IndexLayoutRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.IndexLayoutResponse.SerializeToString,
            ),
            'CacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheStats,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.CacheStatsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.CacheStatsResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.ListObjectsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.ListObjectsResponse.SerializeToString,
            ),
            'DecodeObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DecodeObject,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.DecodeObjectRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.DecodeObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memlake.v1.Memlake', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memlake.v1.Memlake', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Memlake:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/CreateNamespace',
            memlake_dot_v1_dot_memlake__pb2.CreateNamespaceRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.CreateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/DeleteNamespace',
            memlake_dot_v1_dot_memlake__pb2.DeleteNamespaceRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.DeleteNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Write',
            memlake_dot_v1_dot_memlake__pb2.WriteRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Query',
            memlake_dot_v1_dot_memlake__pb2.QueryRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/ListNamespaces',
            memlake_dot_v1_dot_memlake__pb2.ListNamespacesRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Stats',
            memlake_dot_v1_dot_memlake__pb2.StatsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Get',
            memlake_dot_v1_dot_memlake__pb2.GetRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EntityStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/EntityStats',
            memlake_dot_v1_dot_memlake__pb2.EntityStatsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.EntityStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MetadataStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/MetadataStats',
            memlake_dot_v1_dot_memlake__pb2.MetadataStatsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.MetadataStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/LinkStats',
            memlake_dot_v1_dot_memlake__pb2.LinkStatsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.LinkStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Scan',
            memlake_dot_v1_dot_memlake__pb2.ScanRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByPredicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/DeleteByPredicate',
            memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/ListWal',
            memlake_dot_v1_dot_memlake__pb2.ListWalRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.ListWalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexLayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/IndexLayout',
            memlake_dot_v1_dot_memlake__pb2.IndexLayoutRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.IndexLayoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/CacheStats',
            memlake_dot_v1_dot_memlake__pb2.CacheStatsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.CacheStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/ListObjects',
            memlake_dot_v1_dot_memlake__pb2.ListObjectsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.ListObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecodeObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/DecodeObject',
            memlake_dot_v1_dot_memlake__pb2.DecodeObjectRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.DecodeObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
