# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memlake_client.v1 import memlake_pb2 as memlake_dot_v1_dot_memlake__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memlake/v1/memlake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemlakeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNamespace = channel.unary_unary(
                '/memlake.v1.Memlake/CreateNamespace',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/memlake.v1.Memlake/Write',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.WriteRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/memlake.v1.Memlake/Query',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.QueryRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/memlake.v1.Memlake/ListNamespaces',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/memlake.v1.Memlake/Stats',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.StatsRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/memlake.v1.Memlake/Get',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.GetRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/memlake.v1.Memlake/Scan',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.ScanRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.DeleteByPredicate = channel.unary_unary(
                '/memlake.v1.Memlake/DeleteByPredicate',
                request_serializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateRequest.SerializeToString,
                response_deserializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateResponse.FromString,
                _registered_method=True)


class MemlakeServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateNamespace(self, request, context):
        """Ensure a namespace (bank) exists. Idempotent: safe to call on every startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write a batch of ops as one atomic WAL entry. Returns once the entry is durably
        persisted to object storage under a uniquely-claimed sequence number — NOT after
        indexing. The write is immediately visible to any STRONG-consistency Query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Answer a query across one or more memory_types in a single call. Always runs all three
        arms (dense vector + BM25 full-text + graph expansion) over one shared snapshot, so the
        storage reads coalesce into common roundtrip waves. Returns each candidate with its raw
        per-arm scores; the client fuses. memory_types are independent — hits are never fused
        across types.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """---- Admin / introspection ----

        These serve operators and the admin UI, not the hot path. They are answerable by any
        replica for the same reason every other RPC is: the answer lives in object storage.
        They are deliberately NOT part of the retrieval contract — a client doing recall
        should never need them.

        Every namespace in the bucket, by listing manifest objects. Cost is one LIST, so this
        is an operator call, not something to poll per request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """A namespace's index state: generation, WAL position, and per-memory_type doc and
        cluster counts. Reads the manifest and each type's metadata — it does NOT fetch
        cluster data, so its cost is independent of corpus size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Fetch memories by id, without a query. Resolves each id through the primary-key
        SSTable to its cluster, then range-reads only those clusters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Page through a memory_type's stored memories in cluster order. This is a full scan by
        construction — the cost DOES grow with the corpus — so it exists for browsing and
        debugging, never for retrieval. Use `Query` to find things.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByPredicate(self, request, context):
        """Tombstone every memory matching a predicate. The predicate is metadata AND tags (all
        must hold), e.g. `{document_id, chunk_id}` to replace a document's facts on re-ingest.
        A full scan by construction (metadata is not indexed) — a maintenance op, not a query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemlakeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespace,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.CreateNamespaceResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.WriteRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.WriteResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.QueryRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.QueryResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.StatsRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.StatsResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.GetRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.GetResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.ScanRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.ScanResponse.SerializeToString,
            ),
            'DeleteByPredicate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByPredicate,
                    request_deserializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateRequest.FromString,
                    response_serializer=memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memlake.v1.Memlake', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memlake.v1.Memlake', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Memlake:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/CreateNamespace',
            memlake_dot_v1_dot_memlake__pb2.CreateNamespaceRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.CreateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Write',
            memlake_dot_v1_dot_memlake__pb2.WriteRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Query',
            memlake_dot_v1_dot_memlake__pb2.QueryRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/ListNamespaces',
            memlake_dot_v1_dot_memlake__pb2.ListNamespacesRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Stats',
            memlake_dot_v1_dot_memlake__pb2.StatsRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Get',
            memlake_dot_v1_dot_memlake__pb2.GetRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/Scan',
            memlake_dot_v1_dot_memlake__pb2.ScanRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByPredicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memlake.v1.Memlake/DeleteByPredicate',
            memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateRequest.SerializeToString,
            memlake_dot_v1_dot_memlake__pb2.DeleteByPredicateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
